### ISSUE TITLE
Does not compile for embedded platform

### ISSUE THREAD

**Issue by alsaleem00** [compuphase/minIni#16]
I am using minIni for embedded system (ESP32).
The compiler failed at _tcsnicmp --> strnicmp. 
I see that this is defined when __linux is defined (_tcsnicmp --> strncasecmp).
My compiler is gcc which is similar to linux.
Could you add switch for gcc ?

**Comment by compuphase** [comment]
Fixed in commit 51d636f9c60f8d013860965565b447ef14dc2286.

**Comment by alsaleem00** [comment]
thanks.
