### ISSUE TITLE
Minor: Documentation for ini_getbool mentions nonexisting parameters

### ISSUE THREAD

**Issue by tinus-github** [compuphase/minIni#3]
Xcodes analyser notes that the doxygen code for ini_getbool mentions the parameters Buffer and BufferSize, which are not present in the function definition, which appears to be true:

```
/** ini_getbool()
[...]
 * \param Buffer      a pointer to the buffer to copy into
 * \param BufferSize  the maximum number of characters to copy
[...]
int ini_getbool(const TCHAR *Section, const TCHAR *Key, int DefValue, const TCHAR *Filename)
```

I'm not really sure how to note that but I created a pull request here: #4

**Comment by compuphase** [comment]
Merged. Thanks.
