### ISSUE TITLE
remove "const" from UserData for ini_browse

### ISSUE THREAD

**Issue by iweindesmedt** [compuphase/minIni#6]
Just a suggestion for this nice library: user data should not be forced as `const`.

Removing `const` on `UserData` in these lines is enough for this:
https://github.com/compuphase/minIni/blob/master/dev/minIni.h#L59 and line 60
https://github.com/compuphase/minIni/blob/master/dev/minIni.c#L461

**Comment by compuphase** [comment]
Fixed in commit 77908366d4c0a758e33c4c6f39a29eba836ae7dd.
Thanks for the report.
